require('dotenv').config();
const express = require('express'), session = require('express-session'), PgStore = require('connect-pg-simple')(session), bcrypt = require('bcryptjs'), multer = require('multer'), path = require('path');
const db = require('./db');
const app = express();
app.set('view engine','ejs'); app.set('views', path.join(__dirname,'views'));
app.use(express.urlencoded({extended:true})); app.use(express.json()); app.use('/public', express.static(path.join(__dirname,'public')));
app.use(session({store:new PgStore({pool:db.pool,createTableIfMissing:true}), secret:process.env.SESSION_SECRET||'biruta-dev', resave:false, saveUninitialized:false, cookie:{maxAge:1000*60*60*24*7}}));
const upload = multer({storage: multer.diskStorage({destination:'public/uploads', filename:(req,file,cb)=>cb(null,Date.now()+'-'+file.originalname.replace(/\s+/g,'-'))})});
const money = v => Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
async function settings(){ const r=await db.query('SELECT key,value FROM settings'); return Object.fromEntries(r.rows.map(x=>[x.key,x.value])); }
async function years(){ return (await db.query('SELECT * FROM budget_years ORDER BY year')).rows; }
function admin(req,res,next){ if(req.session.user) return next(); res.redirect('/admin/login'); }
app.use(async(req,res,next)=>{res.locals.money=money; res.locals.s=await settings().catch(()=>({})); next();});
app.get('/', async(req,res)=>{ const banners=(await db.query('SELECT * FROM banners WHERE active=true ORDER BY sort_order,created_at DESC')).rows; const promo=(await db.query('SELECT * FROM promotions WHERE active=true AND highlight=true ORDER BY created_at DESC LIMIT 1')).rows[0]; const packs=(await db.query('SELECT p.*,y.year FROM packages p JOIN budget_years y ON y.id=p.year_id WHERE p.active=true AND y.active=true ORDER BY y.year DESC,p.sort_order LIMIT 7')).rows; const deps=(await db.query('SELECT * FROM testimonials WHERE active=true ORDER BY created_at DESC LIMIT 3')).rows; res.render('index',{banners,promo,packs,deps}); });
app.get('/promocoes', async(req,res)=>{ const promos=(await db.query('SELECT * FROM promotions ORDER BY active DESC, created_at DESC')).rows; res.render('promocoes',{promos}); });
app.get('/orcamento', async(req,res)=>{ res.render('orcamento',{years:await years()}); });
app.get('/api/packages', async(req,res)=>{ const year = Number(req.query.year); const r=await db.query('SELECT p.*,y.year FROM packages p JOIN budget_years y ON y.id=p.year_id WHERE y.year=$1 AND y.active=true AND p.active=true ORDER BY p.sort_order',[year]); res.json(r.rows); });
app.post('/api/leads', async(req,res)=>{ const {name,whatsapp,birthday_name,birthday_age,event_date,guests,event_type,wants_food,selected_package_id}=req.body; const p=(await db.query('SELECT p.*,y.year FROM packages p JOIN budget_years y ON y.id=p.year_id WHERE p.id=$1',[selected_package_id])).rows[0]; if(!p) return res.status(400).json({error:'Pacote inválido'}); const g=Number(guests||0), add=Math.max(0,g-Number(p.base_people)); const addTotal=add*Number(p.additional_price), total=Number(p.base_price)+addTotal; const lead=(await db.query('INSERT INTO leads(name,whatsapp,birthday_name,birthday_age,event_date,guests,event_type,wants_food,selected_package_id,year,base_value,additional_guests,additional_total,total) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING *',[name,whatsapp,birthday_name,birthday_age,event_date||null,g,event_type,wants_food,selected_package_id,p.year,p.base_price,add,addTotal,total])).rows[0]; const msg=`Olá! Fiz um orçamento pelo site do Biruta Park.\nNome: ${name}\nWhatsApp: ${whatsapp}\nFesta: ${birthday_name||''} ${birthday_age?'- '+birthday_age+' anos':''}\nData: ${event_date||''}\nConvidados: ${g}\nPacote: ${p.name} para ${p.base_people} pessoas - ${money(p.base_price)}\n${add} convidados adicionais: ${money(p.additional_price)} x ${add} = ${money(addTotal)}\nTotal: ${money(total)}`; res.json({lead,total,add,addTotal,package:p,whatsapp_url:`https://wa.me/${res.locals.s.whatsapp||process.env.WHATSAPP_NUMBER}?text=${encodeURIComponent(msg)}`}); });
app.get('/admin/login',(req,res)=>res.render('admin-login',{error:null}));
app.post('/admin/login',async(req,res)=>{ const u=(await db.query('SELECT * FROM users WHERE email=$1',[req.body.email])).rows[0]; if(u && await bcrypt.compare(req.body.password,u.password_hash)){req.session.user={id:u.id,email:u.email}; return res.redirect('/admin')} res.render('admin-login',{error:'Login ou senha inválidos'}); });
app.get('/admin/logout',(req,res)=>req.session.destroy(()=>res.redirect('/admin/login')));
app.get('/admin',admin,async(req,res)=>{ const leads=(await db.query('SELECT l.*,p.name package_name FROM leads l LEFT JOIN packages p ON p.id=l.selected_package_id ORDER BY l.created_at DESC LIMIT 20')).rows; const counts=(await db.query("SELECT status,count(*) FROM leads GROUP BY status")).rows; res.render('admin',{page:'dashboard',leads,counts}); });
app.get('/admin/orcamentos',admin,async(req,res)=>{ const yrs=await years(); const packs=(await db.query('SELECT p.*,y.year FROM packages p JOIN budget_years y ON y.id=p.year_id ORDER BY y.year DESC,p.sort_order')).rows; res.render('admin',{page:'orcamentos',yrs,packs}); });
app.post('/admin/year',admin,async(req,res)=>{ await db.query('INSERT INTO budget_years(year,active) VALUES($1,$2) ON CONFLICT(year) DO UPDATE SET active=$2',[req.body.year,!!req.body.active]); res.redirect('/admin/orcamentos'); });
app.post('/admin/year/:id/toggle',admin,async(req,res)=>{ await db.query('UPDATE budget_years SET active=NOT active WHERE id=$1',[req.params.id]); res.redirect('/admin/orcamentos'); });
app.post('/admin/package',admin,async(req,res)=>{ const b=req.body; if(b.id) await db.query('UPDATE packages SET name=$1,subtitle=$2,base_people=$3,base_price=$4,card_price=$5,additional_price=$6,duration=$7,availability=$8,included=$9,rules=$10,active=$11,featured=$12 WHERE id=$13',[b.name,b.subtitle,b.base_people,b.base_price,b.card_price||null,b.additional_price,b.duration,b.availability,b.included,b.rules,!!b.active,!!b.featured,b.id]); else await db.query('INSERT INTO packages(year_id,name,subtitle,base_people,base_price,card_price,additional_price,duration,availability,included,rules,active,featured) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)',[b.year_id,b.name,b.subtitle,b.base_people,b.base_price,b.card_price||null,b.additional_price,b.duration,b.availability,b.included,b.rules,!!b.active,!!b.featured]); res.redirect('/admin/orcamentos'); });
app.post('/admin/package/:id/delete',admin,async(req,res)=>{ await db.query('DELETE FROM packages WHERE id=$1',[req.params.id]); res.redirect('/admin/orcamentos'); });
app.get('/admin/site',admin,async(req,res)=>{ const banners=(await db.query('SELECT * FROM banners ORDER BY sort_order')).rows; const promos=(await db.query('SELECT * FROM promotions ORDER BY created_at DESC')).rows; res.render('admin',{page:'site',banners,promos}); });
app.post('/admin/settings',admin,async(req,res)=>{ for(const [k,v] of Object.entries(req.body)) await db.query('INSERT INTO settings(key,value) VALUES($1,$2) ON CONFLICT(key) DO UPDATE SET value=$2',[k,v]); res.redirect('/admin/site'); });
app.post('/admin/banner',admin,upload.single('image'),async(req,res)=>{ const image=req.file?'/public/uploads/'+req.file.filename:req.body.image_url||''; await db.query('INSERT INTO banners(title,subtitle,button_text,button_link,image_url,active,sort_order) VALUES($1,$2,$3,$4,$5,$6,$7)',[req.body.title,req.body.subtitle,req.body.button_text,req.body.button_link,image,!!req.body.active,req.body.sort_order||0]); res.redirect('/admin/site'); });
app.post('/admin/promotion',admin,upload.single('image'),async(req,res)=>{ const image=req.file?'/public/uploads/'+req.file.filename:req.body.image_url||''; await db.query('INSERT INTO promotions(title,description,button_text,link,image_url,starts_at,ends_at,active,highlight) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[req.body.title,req.body.description,req.body.button_text,req.body.link,image,req.body.starts_at||null,req.body.ends_at||null,!!req.body.active,!!req.body.highlight]); res.redirect('/admin/site'); });
app.get('/admin/leads',admin,async(req,res)=>{ const leads=(await db.query('SELECT l.*,p.name package_name FROM leads l LEFT JOIN packages p ON p.id=l.selected_package_id ORDER BY l.created_at DESC')).rows; res.render('admin',{page:'leads',leads}); });
app.post('/admin/leads/:id/status',admin,async(req,res)=>{ await db.query('UPDATE leads SET status=$1,notes=$2 WHERE id=$3',[req.body.status,req.body.notes,req.params.id]); res.redirect('/admin/leads'); });
app.listen(process.env.PORT||3000,()=>console.log('Biruta Park online na porta '+(process.env.PORT||3000)));
