require('dotenv').config();
const bcrypt = require('bcryptjs'); const db = require('../db');
const brl = v => Number(String(v).replace('.','').replace(',','.'));
const data = {
  2026:[['Infantil','20 crianças + 10 pessoas',30,2996,3212,85,'3 horas','Segunda a quarta','Salgados fritos, mini cachorro-quente, bolo, carrinho de picolé, refrigerantes, sucos, convites virtuais, decoração, 4 monitores e 2 garçons.','Crianças de 0 a 2 anos não pagam. Apenas aniversariante não paga.'],['Escolar','40 pessoas',40,4310,null,70,'3 horas','Segunda a quarta','Salgados fritos e assados, mini cachorro-quente, bolo, docinhos, bebidas, convites físico e virtual, decoração, hora do piquenique, monitores, garçons e gerente.','Sem limite de adultos ou crianças dentro das 40 pessoas.'],['Birutinha','50 pessoas',50,5750,null,75,'3 horas','Segunda a sexta','Salgados fritos e assados, mini cachorro-quente, bolo, docinhos, bebidas, convites, decoração 111 festas, monitores, garçons e parabéns especial.','Crianças de 0 a 5 anos não pagam. Mamãe, papai, aniversariante e até 2 irmãos não pagam.'],['Biruta sem massa','50 pessoas',50,6650,null,80,'4 horas','Segunda a sábado','Salgados fritos e assados, mini cachorro-quente, mini cheese burguer, carrinho de picolés, bolo, docinhos, bebidas, convites e decoração 111 festas.','Sem limite de adultos ou crianças. Carrinho de picolé servido após o piquenique.'],['Biruta com massa','50 pessoas',50,7190,null,85,'4 horas','Segunda a sábado','Inclui itens do Biruta sem massa + finger food: conchilli 4 queijos ao molho sugo.','Sem limite de adultos ou crianças.'],['Cheff','50 pessoas',50,7640,null,90,'4 horas','Todos os dias e feriados','Salgados fritos, mini cachorro-quente, mini cheese burguer, pizzas no sistema pega pizza, carrinho de picolés, bolo, docinhos, bebidas, convites e decoração.','Sem limite de adultos ou crianças.'],['Gourmet','50 pessoas',50,7910,null,90,'4 horas','Todos os dias e feriados','Salgados fritos e assados, mini cachorro-quente, mini cheese burguer, finger food, saladinha gourmet, carrinho de picolés, bolo, docinhos, bebidas, convites e decoração.','Sem limite de adultos ou crianças.']],
  2027:[['Infantil','20 crianças + 10 pessoas',30,3491,3734,90,'3 horas','Segunda a quarta','Salgados fritos, mini cachorro-quente, bolo, carrinho de picolé, refrigerantes, sucos, convites virtuais, decoração, 4 monitores e 2 garçons.','Crianças de 0 a 2 anos não pagam. Apenas aniversariante não paga.'],['Escolar','40 pessoas',40,4850,null,75,'3 horas','Segunda a quarta','Salgados fritos e assados, mini cachorro-quente, bolo, docinhos, bebidas, convites físico e virtual, decoração, hora do piquenique, monitores, garçons e gerente.','Sem limite de adultos ou crianças dentro das 40 pessoas.'],['Birutinha','50 pessoas',50,6200,null,80,'3 horas','Segunda a sexta','Salgados fritos e assados, mini cachorro-quente, bolo, docinhos, bebidas, convites, decoração 111 festas, monitores, garçons e parabéns especial.','Crianças de 0 a 5 anos não pagam. Mamãe, papai, aniversariante e até 2 irmãos não pagam.'],['Biruta sem massa','50 pessoas',50,7100,null,85,'4 horas','Segunda a sábado','Salgados fritos e assados, mini cachorro-quente, mini cheese burguer, carrinho de picolés, bolo, docinhos, bebidas, convites e decoração 111 festas.','Sem limite de adultos ou crianças. Carrinho de picolé servido após o piquenique.'],['Biruta com massa','50 pessoas',50,7640,null,90,'4 horas','Segunda a sábado','Inclui itens do Biruta sem massa + finger food: conchilli 4 queijos ao molho sugo.','Sem limite de adultos ou crianças.'],['Cheff','50 pessoas',50,8090,null,95,'4 horas','Todos os dias e feriados','Salgados fritos, mini cachorro-quente, mini cheese burguer, pizzas no sistema pega pizza, carrinho de picolés, bolo, docinhos, bebidas, convites e decoração.','Sem limite de adultos ou crianças.'],['Gourmet','50 pessoas',50,8450,null,95,'4 horas','Todos os dias e feriados','Salgados fritos e assados, mini cachorro-quente, mini cheese burguer, finger food, saladinha gourmet, carrinho de picolés, bolo, docinhos, bebidas, convites e decoração.','Sem limite de adultos ou crianças.']]
};
(async()=>{
 await db.query(require('fs').readFileSync(require('path').join(__dirname,'..','schema.sql'),'utf8'));
 const email=process.env.ADMIN_EMAIL||'admin@birutapark.com.br', pass=process.env.ADMIN_PASSWORD||'admin123';
 await db.query('INSERT INTO users(email,password_hash,name) VALUES($1,$2,$3) ON CONFLICT(email) DO NOTHING',[email, await bcrypt.hash(pass,10),'Biruta Park']);
 const settings = {site_title:'Buffet Biruta Park', whatsapp:process.env.WHATSAPP_NUMBER||'5516997913686', instagram:'https://instagram.com/birutapark', address:'Rua Dr. Carlos Kielander, Nº15 - Centro - Monte Alto - SP', footer_text:'© Buffet Biruta Park — Deixe a diversão te guiar!', hero_title:'A festa perfeita começa aqui!', hero_subtitle:'Conheça nossa estrutura e monte seu orçamento online em poucos passos.'};
 for (const [k,v] of Object.entries(settings)) await db.query('INSERT INTO settings(key,value) VALUES($1,$2) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value',[k,v]);
 await db.query("INSERT INTO banners(title,subtitle,button_text,button_link,active,sort_order) VALUES('Orçamento online','Monte uma simulação personalizada para sua festa.','Fazer meu orçamento','/orcamento',true,1) ON CONFLICT DO NOTHING");
 await db.query("INSERT INTO promotions(title,description,button_text,link,active,highlight) VALUES('Promoção do mês','Participe da nossa campanha especial e descubra seu presente.','Participar agora','https://mesdasmaes.birutapark.com.br',true,true) ON CONFLICT DO NOTHING");
 let order=0; for (const [year, packs] of Object.entries(data)) { let yr = await db.query('INSERT INTO budget_years(year,active) VALUES($1,true) ON CONFLICT(year) DO UPDATE SET active=true RETURNING id',[year]); let id=yr.rows[0].id; for(const p of packs){order++; await db.query('INSERT INTO packages(year_id,name,subtitle,base_people,base_price,card_price,additional_price,duration,availability,included,rules,sort_order,active) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,true)',[id,...p,order]);}}
 console.log('Seed concluído. Login:', email, 'Senha:', pass); process.exit(0);
})().catch(e=>{console.error(e);process.exit(1)});
